name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the article PDF
    concurrency: showyourwork-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clone ebtel++
        uses: actions/checkout@v4
        with:
          repository: jwreep/ebtelPlusPlus
          ref: main
          path: ebtelPlusPlus # Store in $GITHUB_WORKSPACE/ebtelPlusPlus

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          conda config --set channel_priority strict
          pip install scons
          sudo apt-get update
          sudo apt-get install libboost-all-dev
          
      - name: Install ebtel++
        run: |
          cd $GITHUB_WORKSPACE/ebtelPlusPlus
          scons
          cd ..
        
      - name: Build the article PDF
        id: build
        with:
          showyourwork-spec: git+https://github.com/showyourwork/showyourwork
        uses: showyourwork/showyourwork-action@v1
        env:
          EBTELPLUSPLUS_DIR: ${{ github.workspace }}/ebtelPlusPlus
#          SANDBOX_TOKEN: ${{ secrets.SANDBOX_TOKEN }}
          OVERLEAF_EMAIL: ${{ secrets.OVERLEAF_EMAIL }}
          OVERLEAF_PASSWORD: ${{ secrets.OVERLEAF_PASSWORD }}
